title: Website von Flanntierchen
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: gfm
logo: /assets/img/logo.png
github:
  is_project_page: false
  is_user_page: false
social:
  - name: Twitch
    url: https://www.twitch.tv/flanntierchen
    icon: https://static.twitchcdn.net/assets/favicon-32-e29e246c157142c94346.png
  - name: Instagram
    url: https://www.instagram.com/flanntierchen/
    icon: https://static.cdninstagram.com/rsrc.php/v3/yt/r/30PrGfR3xhB.png
  - name: Discord
    url: https://discord.gg/y83WbsKhhQ
    icon: https://discord.com/assets/847541504914fd33810e70a0ea73177e.ico
  - name: YouTube
    url: https://www.youtube.com/channel/UCtwa3BQZ8_g9Ni0Vrh0DSbA
    icon: https://www.youtube.com/s/desktop/17050e65/img/favicon.ico
  - name: TikTok
    url: https://www.tiktok.com/@Flanntierchen
    icon: https://lf16-tiktok-web.ttwstatic.com/obj/tiktok-web-common-sg/mtact/static/images/logo_144c91a.png
