title: Ein Floh
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: gfm
logo: /assets/img/Logo.png
github:
  is_project_page: false
  is_user_page: false
social:
  - name: Twitch
    url: https://www.twitch.tv/einfloh
  - name: Youtube
    url: https://www.youtube.com/@ein_floh
  - name: Instagram
    url: https://www.instagram.com/ein.flohh/
  - name: Discord
    url: https://discord.gg/y83WbsKhhQ
