title: Ein Floh
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: gfm
logo: /assets/img/Logo.png
github: 
  is_project_page: false
  is_user_page: false
facebook_url: https://www.twitch.tv/einfloh
youtube_url: https://www.youtube.com/@ein_floh
linkedin_url: https://discord.gg/y83WbsKhhQ
instagram_url: https://www.instagram.com/ein.flohh/
